name: "project vulnerability check (semgrep)"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
      - uses: actions/checkout@v4

      - name: setup python
      - uses: actions/checkout@v4
        with:
          python-version: '3.x'

      - name: install semgrep
        run: pip install Semgrep

      - name: run semgrep
        run: semgrep --config auto --error || true