name: "project vulnerability check (semgrep)"

on:
  push:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: install semgrep
        run: pip install Semgrep

      - name: run semgrep
        run: |
          mkdir -p reports
          # Run Semgrep and save JSON report (always creates a file, even if no findings)
          semgrep --config auto --json > reports/semgrep-report.json || true
          # Touch file to guarantee it exists if semgrep fails unexpectedly
          touch reports/semgrep-report.json

      - name: upload semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: reports/semgrep-report.json